FROM node:20-alpine
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY nest-cli.json tsconfig*.json ./
COPY apps ./apps
COPY libs ./libs

CMD ["sh", "-c", "npx nest start --watch $APP_NAME"]
